#!/bin/bash


# Copyright (C) 2016 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


##### Script to check whether the files openjdk_java_files.mk match
##### those in the corresponding directory.
COMMAND='diff <(for i in $(openjdk_java_files); do echo "\$$i"; done | sort) '
COMMAND=${COMMAND}'<( find ojluni/src/main/java -type f | grep '\''\.java$$'\'' | sort )'

# Need to do it this nasty way (creating a Makefile on the fly and
# executing the bash command inside it) as to read the openjdk_java_files
# variable from an .mk file.
make -s -f <(cat <<EOF
include openjdk_java_files.mk
check_openjdk_java_files: ; /bin/bash -c "$COMMAND"
EOF)

if [ $? -eq 0 ]; then
    echo 'No differences found'
else
    echo 'Differences found'
    exit 1
fi

